### PR TITLE
v1.0.0 (beta)

### PR DESCRIPTION
**Pull request by byanko55**
*Bug Fix*
* Subject icon has non-circular border
* Liquid syntax error (but, not severe)

### CODE REVIEW

**Review by cvlian — COMMENTED** [review]
From `safari 16`, the sizes of circle symbols are not equal.
image

See also:
image

**Comment by byanko55** [comment]
Adding `font-family: cursive;` resolve it.

**Review by cvlian — APPROVED** [review]
That’s great.

**Review by mgarrixx — CHANGES_REQUESTED** [review]
Everything seems fine. But before closing this PR, please try a build test using local gem package.

**Comment by byanko55** [comment]
I had tested successfully. See my work in [Rubygem archive](https://rubygems.org/gems/jekyll-professional-resume)

You're going to have to write a manual (or update README.md) regarding the installation via rubygem package.

**Review by mgarrixx — APPROVED** [review]
Got it. I’ll do it right away.

**Pull request merged**
