### PR TITLE
Hot fix: v1.0.0

### PR DESCRIPTION
**Pull request by byanko55**
**Bug Fix**
* Name/Job field were missed in configuration (`_config.yml`)
* Site icon is not displaying
* Unable to update the profile image

### CODE REVIEW

**Review by cvlian — APPROVED** [review]
You'd almost missed out one of the most important thing..

**Comment by cvlian** [comment]
@mgarrixx, Don't forget to add fields regarding to user's name/job in this [section](https://github.com/byanko55/jekyll-professional-resume#customizing).

**Comment by mgarrixx** [comment]
I found that disabling a site variable in `_config.yml` does not affect the rendered output. e.g., I commented in front of the *blog_url*, but the test page still showing the homepage icon and default value(`homepage-url`) on #about section. 

Besides, the contents in `_data` still appear even after I removed the corresponding YAML file.

Downgrading Jekyll version to `3.9` solves this issue for me. Could you inspect such an issue in more detail?

**Review by mgarrixx — APPROVED** [review]
Good, That will be helpful.

**Comment by byanko55** [comment]
> I found that disabling a site variable in `_config.yml` does not affect the rendered output. e.g., I commented in front of the _blog_url_, but the test page still showing the homepage icon and default value(`homepage-url`) on #about section.
> 
> Besides, the contents in `_data` still appear even after I removed the corresponding YAML file.
> 
> Downgrading Jekyll version to `3.9` solves this issue for me. Could you inspect such an issue in more detail?

I blocked the use of `jekyll > 4` at this patch. Surely the issue must be handled with care. Thank you for the important findings!

**Pull request merged**
