### PR TITLE
v1.0.1

### PR DESCRIPTION
**Pull request by byanko55**
**Bug Fixes**
* Irregular site appears when the repo name does not follow "[user-name].github.io"
* E-mail button open a 404 page

### CODE REVIEW

**Comment by byanko55** [comment]
I just opened a [demo repo](https://github.com/byanko55/resume-demo). Visit there and take a look, @cvlian, @mgarrixx

**Comment by cvlian** [comment]
image

Bullets do not disappear.

**Comment by byanko55** [comment]
Now check that bullet again.

**Review by cvlian — APPROVED** [review]
Turns out that if the baseurl is not given, Jekyll considers `/` as the root of your website even though you already have a repo activating github.io. Kinda good finding.

I checked all. Thanks.

**Review by mgarrixx — APPROVED** [review]
I’m done too.

**Pull request merged**
